create table products (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_name text not null,
    product_roast text not null,
    price NUMERIC not NULL,
    picture_main text not null,
    details text not null,
    date_created TIMESTAMP NOT NULL DEFAULT now(),
    origin text not null,
    collection text not null,
    sale boolean DEFAULT FALSE,
    sale_price NUMERIC null,
    featured boolean DEFAULT FALSE
)

/*  */



